services:
  - type: web
    name: flitz
    env: node
    plan: starter
    buildCommand: yarn --frozen-lockfile --prod=false &&
      blitz build && cp -r .blitz/build/.next .
    startCommand: blitz start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: flitz-database
          property: connectionString

databases:
  - name: flitz-database
    plan: starter
